### ISSUE TITLE
Missing opacity from TiledLayer

### ISSUE THREAD

**Issue by juanferrer** [TheBoneJarmer/TiledCS#77] opened 2022-07-26 12:32 UTC
One of the attributes in the resulting XML for a layer is opacity, I noticed `TiledLayer` doesn't have this property. Are you accepting PRs?

**Comment by TheBoneJarmer** [comment] 2022-07-26 13:01
Just checked and confirmed. And yes, I do accept pull requests but due to this change being so tiny I decided to  just add it myself in the develop branch. If you need it asap feel free to pull it and build it. I have to focus at something else right now so will probably test it thoroughly this evening probably so I can merge it to master. :)

**Comment by TheBoneJarmer** [comment] 2022-08-05 12:26
Fix has been released!

**Closed by TheBoneJarmer** 2022-08-05 12:26 UTC
Labels: feature
